name = "karimasyari-frontend"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[vars]
VENDURE_API_URL = "https://api.karimasyari.com/shop-api"
VENDURE_TOKEN_NAME = "vendure-auth-token"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "8d883fa195054f46964e8399341b30cb"
preview_id = "KV_CACHE_PREVIEW"
